
// This file has been generated by the GUI designer. Do not modify.
namespace PArticuloMejorado
{
	public partial class VentanaEditar
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label nombreLabel;
		private global::Gtk.Entry entry1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label precioLabel;
		private global::Gtk.SpinButton spinbutton1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label categoriaLabel;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button Guardar;
		private global::Gtk.Button Cancelar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticuloMejorado.VentanaEditar
			this.Name = "PArticuloMejorado.VentanaEditar";
			this.Title = global::Mono.Unix.Catalog.GetString ("Editar item");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PArticuloMejorado.VentanaEditar.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.nombreLabel = new global::Gtk.Label ();
			this.nombreLabel.Name = "nombreLabel";
			this.nombreLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.hbox1.Add (this.nombreLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.nombreLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w2.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.precioLabel = new global::Gtk.Label ();
			this.precioLabel.Name = "precioLabel";
			this.precioLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio:    ");
			this.hbox2.Add (this.precioLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.precioLabel]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spinbutton1 = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10;
			this.spinbutton1.ClimbRate = 1;
			this.spinbutton1.Numeric = true;
			this.hbox2.Add (this.spinbutton1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spinbutton1]));
			w5.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.categoriaLabel = new global::Gtk.Label ();
			this.categoriaLabel.Name = "categoriaLabel";
			this.categoriaLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoría:");
			this.hbox3.Add (this.categoriaLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.categoriaLabel]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.hbox3.Add (this.combobox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.combobox1]));
			w8.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.Guardar = new global::Gtk.Button ();
			this.Guardar.CanFocus = true;
			this.Guardar.Name = "Guardar";
			this.Guardar.UseUnderline = true;
			this.Guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.hbox4.Add (this.Guardar);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Guardar]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.Cancelar = new global::Gtk.Button ();
			this.Cancelar.CanFocus = true;
			this.Cancelar.Name = "Cancelar";
			this.Cancelar.UseUnderline = true;
			this.Cancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox4.Add (this.Cancelar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Cancelar]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 395;
			this.DefaultHeight = 172;
			this.Show ();
		}
	}
}
