
// This file has been generated by the GUI designer. Do not modify.
namespace Serpis.Ad
{
	public partial class AplicationContext
	{
		public virtual void Build ()
		{
			// Action group Serpis.Ad.AplicationContext
		}
	}
}
